eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka
server:
  port: 1115
spring:
  application:
    name: consumer-service
feign:
  hystrix:
    enabled: true #在Feign中开启Hystrix
logging:
  level:
    com.jeason.providerclient.client.ProviderClient: debug