spring:
  application:
    name: provider
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka
server:
  port: 1113
info:
  company.name: www.abc.com
  company.addr: China Beijin
  company.tel: 1234
  app.name: provider
  author: jeason